name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy on"
        required: true
        type: choice
        options:
          - development
          - production
      force_deploy:
        description: "Clear"
        required: true
        type: choice
        options:
          - yes
          - no
        default: yes

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.target}}
    env:
      TARGET: ${{inputs.target}}
      CLEAR: ${{inputs.force_deploy}}
    steps:
      - name: show target
        run: |
          echo "We are using target - $TARGET, clear - $CLEAR"
          printenv
          pwd
          ls -alFh
      
