name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy on"
        required: true
        type: choice
        options:
          - development
          - production
        default: production
      force_deploy:
        description: "Clear"
        required: true
        type: choice
        options:
          - yes
          - no
        default: yes

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.target}}
    env:
      ALLMYSECRETS: ${{ toJSON(secrets) }}
      ALLMYVARS: ${{ toJSON(vars) }}
    steps:
      - name: show target
        run: |
          mkdir saver
          chmod 777 saver
          # Save ALLMYSECRETS and ALLMYVARS to files
          echo $ALLMYSECRETS > secrets.json
          echo $ALLMYVARS > var.json

          jq -r 'del(.GITHUB_TOKEN,.github_token)|to_entries|map("\(.key)=\(.value|tostring|@sh)")|.[]' secrets.json > ./saver/.env.secrets
          jq -r 'to_entries | map("\(.key)=\(.value|tostring|@sh)") | .[]' var.json      > ./saver/.env.vars

          ls -l ./saver
      - name: Zip both files
        run: |
          zip -r ./saver.zip ./saver
      - name: Upload zipped files
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: ./saver.zip
  download_artifacts:
    runs-on: ubuntu-latest
    needs: deploy # Ensures this job runs only after the 'deploy' job completes
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: ./downloaded_files # Downloads the artifacts to a specified directory

      - name: List downloaded files
        run: ls -l ./downloaded_files
