name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy on?"
        required: true
        type: choice
        options:
          - dev
          - prod
      force-deploy:
        description: "Clear?"
        required: true
        options:
          - yes
          - no
        default: yes

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    env:
      TARGET: ${{inputs.target}}
      CLEAR: ${{inpits.force-deploy}}
    steps:
      - name: show target
        run: |
          echo "We are using target - $TARGET, clear - $CLEAR"
      
