name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy on"
        required: true
        type: choice
        options:
          - development
          - production
      force_deploy:
        description: "Clear"
        required: true
        type: choice
        options:
          - yes
          - no
        default: yes
env:
  TARGET: ${{inputs.target}}
  CLEAR: ${{inputs.force_deploy}}
  TEST__USERNAME: ${{secrets.TEST__USERNAME}}
  TEST__PASSWORD: ${{vars.TEST__PASSWORD}}
  ALLMYSECRETS: ${{ toJSON(secrets) }}
  ALLMYVARS: ${{ toJSON(vars) }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.target}}
    steps:
      - name: show target
        run: |
          echo "We are using target - $TARGET, clear - $CLEAR"
          echo "TEST__USERNAME: $TEST__USERNAME"
          echo "TEST__PASSWORD: $TEST__PASSWORD"
